routes/web.php
<?php


/**
 * Rotas protegidas por login e senha no painel admin
 */

Route::group(
    [
        'middleware'    =>  ['auth'],   /*requer autenticacao para todos os controles*/
        'namespace'     =>  'Admin',    /*todos controller estão dentro da pasta (namespace) Admin*/
        'prefix'        =>  'admin'     /*Atribui o prefixo 'admin' às todas as rotas referentes ao admin */
    ],
    function(){
        //pagina inicial do admin
        Route::get('/', 'AdminController@index')->name('admin.home');

        //pagina de usuarios sem permissao
        Route::get('/unauthorized', 'AdminController@unauthorized')->name('admin.unauthorized');


        //Escolha do Orgao ao logar
        Route::view('/set_orgao', 'admin.users.set_orgao')->name('users.seta_orgao');


        //rotas adicionais
        Route::get('permissions/roles', 'PermissionController@permissionroleindex')->name('permissions.roles.index');
        Route::post('permissions/roles', 'PermissionController@permissionroleupdate')->name('permissions.roles.update');


        //rotas JSON
        Route::get('orgaos/json', 'OrgaoController@json')->name('orgaos.json');
        Route::get('setores/json', 'SetorController@json')->name('setores.json');
        Route::get('roles/json', 'RoleController@json')->name('roles.json');
        Route::get('permissions/json', 'PermissionController@json')->name('permissions.json');
        Route::get('users/json', 'UserController@json')->name('users.json');


        //Rotas para Users/Roles
        Route::post('users/{user_id}/roles/destroy', 'RoleUserController@destroy')->name('users.roles.destroy');
        Route::get('users/{user_id}/roles',  'RoleUserController@index')->name('users.roles.index');
        Route::post('users/{user_id}/roles', 'RoleUserController@store')->name('users.roles.store');



        //Rotas Padrao CRUD
        Route::resources([
            'orgaos'        =>  'OrgaoController',
            'setores'        =>  'SetorController',
            'roles'         =>  'RoleController',
            'permissions'   =>  'PermissionController',
            'users'         =>  'UserController',
        ]);

    }
);



/**
 * Rotas Para o frontend
 */
Route::group(
    [
        'namespace'     =>  'Portal',    /*todos controller estão dentro da pasta (namespace) Portal*/
    ],
    function(){

        //rota de login e logout
        Route::post('/entrar', 'CadastroController@login')->name('portal.login');
        Route::get('/sair', 'CadastroController@logout')->name('portal.logout');


        Route::get('users/json', 'CadastroController@userJson')->name('portal.users.json');


        /*Rotas do cadastro*/
        //rotas get ou post para as etapas do cadastro
        Route::get('/cadastro/{etapa_id}/etapa', 'CadastroController@index')->name('portal.cadastro.etapa1');
        Route::post('/cadastro/{etapa_id}/etapa', 'CadastroController@index')->name('portal.cadastro.etapas');
        Route::put('/cadastro/{etapa_id}/etapa', 'CadastroController@storeBeneficiario')->name('portal.cadastro.store');
        //redireciona o usuario para a etapa 1 do cadastro
        Route::redirect('/cadastro', '/cadastro/1/etapa', 301);

        /*Rotas de reinicialização de senha*/
        //rotas get ou post para as etapas do senha
        Route::get( '/senha/{etapa_id}/etapa', 'CadastroController@senha')->name('portal.senha.etapa1');
        Route::post('/senha/{etapa_id}/etapa', 'CadastroController@senha')->name('portal.senha.etapas');
        Route::put( '/senha/{etapa_id}/etapa', 'CadastroController@storeNovaSenha')->name('portal.senha.store');
        //redireciona o usuario para a etapa 1 do cadastro
        Route::redirect('/senha', '/senha/1/etapa', 301);


        //pagina inicial do admin
        Route::get('/', 'PortalController@index')->name('portal.home');
    }
);

/**
 * Rotas Para o frontend [AUTENTICADO]
 */
Route::group(
    [
        'middleware'    =>  ['auth'],   /*requer autenticacao para todos os controles*/
        'namespace'     =>  'Portal',    /*todos controller estão dentro da pasta (namespace) Admin*/
        'prefix'        =>  'painel'     /*Atribui o prefixo 'admin' às todas as rotas referentes ao admin */
    ],
    function(){
        //pagina inicial do painel
        Route::get('/', 'PainelController@index')->name('portal.painel');

        //dados do usuario
        Route::get('/dados', 'CadastroController@cadastro')->name('portal.painel.dados');
        Route::post('/dados', 'CadastroController@cadastroUpdate')->name('portal.painel.dados.update');

        //pagina de usuarios sem permissao
        Route::get('/unauthorized', 'CadastroController@unauthorized')->name('portal.unauthorized');

    }
);





Auth::routes();

app/Http/Controllers/Portal/CadastroController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\UserAdmin;
use App\Models\Role;
use App\Models\Role_User;
use Validator;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Auth;



class CadastroController extends Controller
{
    public function index(Request $request, $etapa_id)
    {
        switch ($etapa_id){
            case 1: return view('portal.cadastro.index',['overlay'=>['title'=>'Cadastro de Cidadão','view'=>'portal.cadastro.etapa1'],'rota'=>['portal.cadastro.etapas',2]]);
            case 2:
                //se passou nascimento
                if($request->filled('nascimento') && $request->filled('sexo')){
                    //caclula a diferença em meses entre as datas atual e nascimento
                    $datetime1 = date_create($request->input('nascimento'));
                    $datetime2 = date_create("now");
                    $interval = date_diff($datetime1, $datetime2);
                   //se da dirença for
                    if( (($interval->y*12)+$interval->m) >= config('parametrizacao.frontend_cadastro_idade_minima_meses')){
                        return view('portal.cadastro.index',['overlay'=>['title'=>'Cadastro de Cidadão','view'=>'portal.cadastro.etapa2'],'nascimento'=>$request->input('nascimento'),'sexo'=>$request->input('sexo'),'rota'=>['portal.cadastro.etapas',3]]);
                    }

                }
                //gera o erro
                return redirect()->route('portal.cadastro.etapa1',1) ->withErrors(["nascimento"=>"O cidadão deve informar uma data de nascimento e deve possuir pelo menos 6 meses de vida.<br>É preciso selecionar o sexo."]);
            case 3:
                //verifica se passou os campos nome e nascimento
                if($request->filled('sexo') && $request->filled('nascimento') && $request->filled('nome_completo')){
                    //se selecionou algum usuário já existente
                    if( intval($request->input('nome_completo')) != 0){
                        /*se passou um usuário já existente, redireciona para login com mensagem de erro*/
                        return view('portal.home.index',['overlay'=>['title'=>'Atenção!','html'=>'Já existe um usuário com este mesmo nome e data de nascimento. Por favor, faça o login.','close'=>true]]);
                    }
                    $variaveis = ['nascimento'=>$request->input('nascimento'),'sexo'=>$request->input('sexo'),'nome_completo'=>$request->input('nome_completo')];

                    //calcula a diferença em anos entre as datas atual e nascimento, para ver se necessita responsavel
                    $datetime1 = date_create($request->input('nascimento'));
                    $datetime2 = date_create("now");
                    $interval = date_diff($datetime1, $datetime2);
                    if( $interval->y < config('parametrizacao.frontend_cadastro_idade_minima_responsavel')){
                        $variaveis['responsavel']=1;
                    }

                    $variaveis['rota'] = ['portal.cadastro.etapas',3] ;

                    return view('portal.cadastro.etapa3',$variaveis);
                }
        }


    }

    /**
     * Retorna um objeto datatables
     * @param Request $request
     * @return mixed
     */
    public function userJson(Request $request)
    {
        $datatablejson = new UserAdmin();
        return $datatablejson->dataTable($request);
    }



    public function storeBeneficiario(Request $request)
    {
        /*se passou um usuário já existente, redireciona para login com mensagem de erro*/
        if( intval($request->input('name')) != 0){
            return view('portal.home.index',['overlay'=>['title'=>'Atenção!','html'=>'Já existe um usuário com este mesmo nome e data de nascimento. Por favor, faça o login.','close'=>true]]);
        }

        //variaveis a serem passadas para a view
        $variaveis = [];

        //calcula a diferença em anos entre as datas atual e nascimento, para ver se necessita responsavel
        $datetime1 = date_create($request->input('nascimento'));
        $datetime2 = date_create("now");
        $interval = date_diff($datetime1, $datetime2);
        if( $interval->y < config('parametrizacao.frontend_cadastro_idade_minima_responsavel')){
            $variaveis['responsavel']=1;
        }else{
            $variaveis['responsavel']=2;
        }


        //agrupa os campos enviados pelo request
        $fieldsFromRequest = $request->all();



        $validadores =  [
            'name' =>       'required|min:5|max:255',
            'nascimento' => 'required|date',
            'sexo' =>       'required',
            'saude' =>      'max:255',

            'celular' =>    'required_without:outrofone',
            'outrofone' =>  'required_without:celular',

            'cpf' =>        'required|min:11|max:50|unique:users,cpf',
            'senha' =>      'required|confirmed|min:6',

        ];


        if($request->filled('email')) {
            $validadores['email'] = 'email|unique:users,email';
        }
        if($request->filled('celular')) {
            $fieldsFromRequest['celular'] = str_replace('_', '', $fieldsFromRequest['celular']);
        }
        if($request->filled('outrofone')) {
            $fieldsFromRequest['outrofone'] = str_replace('_', '', $fieldsFromRequest['outrofone']);
        }
        if($request->filled('responsavel_fone')) {
            $fieldsFromRequest['responsavel_fone'] = str_replace('_', '', $fieldsFromRequest['responsavel_fone']);
            $validadores['responsavel_fone'] = 'required|min:13|max:15';
        }
        if($request->filled('responsavel_nome')) {
            $validadores['responsavel_nome'] = 'required|min:5|max:255';
        }
        if($request->filled('responsavel_cpf')) {
            $validadores['responsavel_cpf'] = 'required|min:11|max:50';
        }



        //valida os campos enviados
        $validator = Validator::make($fieldsFromRequest,$validadores);

        //se falhou validação, envia novamente para o formulário
        if ($validator->fails()) {
            return view('portal.cadastro.etapa3')->withErrors($validator)->with($fieldsFromRequest)->with($variaveis);
        }

        //cria uma instancia do Usuário
        $novoUsuario = new UserAdmin();
        //atribui todos os campos
        $novoUsuario->name = $fieldsFromRequest['name'];
        $novoUsuario->email = $fieldsFromRequest['email'];
        $novoUsuario->password = Hash::make($fieldsFromRequest['senha']);
        $novoUsuario->nascimento = $fieldsFromRequest['nascimento'];
        $novoUsuario->cpf = $fieldsFromRequest['cpf'];
        if($request->filled('celular'))
            $novoUsuario->celular = $fieldsFromRequest['celular'];
        if($request->filled('outrofone'))
            $novoUsuario->outrofone = $fieldsFromRequest['outrofone'];
        $novoUsuario->sexo = $fieldsFromRequest['sexo'];
        if($request->filled('saude'))
            $novoUsuario->saude = $fieldsFromRequest['saude'];
        if($request->filled('responsavel_nome')) {
            $novoUsuario->responsavel_nome = $fieldsFromRequest['responsavel_nome'];
            $novoUsuario->responsavel_fone = $fieldsFromRequest['responsavel_fone'];
            $novoUsuario->responsavel_cpf = $fieldsFromRequest['responsavel_cpf'];
        }

        //salva e insere no banco o novo usuário
        if($novoUsuario->save()){//se inseriu com sucesso
            //recupera o id do papel GUEST
            $role_guest_id = Role::where('name','GUEST')->get()->first()->id;
            //Atribui o papel GUEST ao novo usuário
            Role_User::firstOrCreate(['user_id'=>$novoUsuario->id,'role_id'=>$role_guest_id]);
            return view('portal.home.index',['overlay'=>['title'=>'Cadastrado com Sucesso','html'=>'Você concluiu seu cadastro com sucesso. A partir de agora você pode usufruir dos programas, ações e eventos da prefeitura.','close'=>true]]);
        }

        //se houve erro no cadastro
        return view('portal.cadastro.etapa3',['overlay'=>['title'=>'Erro ao gravar dados','html'=>'Tente novamente ou entre em contato com a central de atendimento através do telefone '.config('parametrizacao.fone_central_atendimento'),'close'=>true]])->with($fieldsFromRequest)->with($variaveis);

    }




    /**
     * Controla o processo de reinicialização da senha
     */
    public function senha(Request $request, $etapa_id)
    {
        switch ($etapa_id){
            case 1: return view('portal.cadastro.index',['overlay'=>['title'=>'Reiniciar Senha','html'=>'Confirme seus dados para prosseguir','view'=>'portal.cadastro.etapa1'],'rota'=>['portal.senha.etapas',2]]);
            case 2:
                //se passou nascimento
                if($request->filled('nascimento') && $request->filled('sexo')){
                    return view('portal.cadastro.index',['overlay'=>['title'=>'Reiniciar Senha','view'=>'portal.cadastro.etapa2'],'nascimento'=>$request->input('nascimento'),'sexo'=>$request->input('sexo'),'rota'=>['portal.senha.etapas',3]]);
                }
                //gera o erro
                return redirect()->route('portal.senha.etapa1',1) ->withErrors(["nascimento"=>"O cidadão deve informar uma data de nascimento.<br>É preciso selecionar o sexo."]);
        }


    }


    public function storeNovaSenha(Request $request)
    {
        //variaveis a serem passadas para a view
        $variaveis = [];

        //agrupa os campos enviados pelo request
        $fieldsFromRequest = $request->all();


        //Seleciona o usuário
        if(intval($request->filled('name'))!=0) {
            $novoUsuario = UserAdmin::find($request->filled('name'));
        }
        else {
            $novoUsuario = UserAdmin::find($request->filled('id'));
        }



        $fieldsFromRequest['name'] = $novoUsuario->name;

        $validadores = [

app/Http/Controllers/Portal/PainelController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PainelController extends Controller
{
    public function index(){
        return view('portal.painel.index');

    }
}

app/Http/Controllers/Portal/PortalController.php
<?php

namespace App\Http\Controllers\Portal;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class PortalController extends Controller
{

    public function index()
    {
        return view('portal.home.index');
    }
}
/*
['overlay'=>['title'=>'Recuperação de Senha','html'=>"<p>Meu <strong>negrito </strong>texto html</p>",'close'=>true]]
*/

resources/views/portal/cadastro/etapa1.blade.php
{!! Form::open(['route' => $rota]) !!}

<div class="form-group">
    <label>Data de Nascimento</label>
    <div class="input-group">
        <div class="input-group-addon"><i class="fa fa-calendar"></i></div>
        {!! Form::text('nascimento',null,['id' => 'nascimento','class' => 'form-control','required'=>true]) !!}
    </div>
</div>

<div class="form-group">
    <label>Sexo</label>
    <div class="input-group" style="background-color: white">
        <div class="input-group-addon"><i class="fa fa-venus-mars"></i></div>
        <select name="sexo" id="sexo" class="form-control" style="border-radius: 0px;" required>
            <option value="0">Selecione</option>
            <option value="m">Masculino</option>
            <option value="f">Feminino</option>
        </select>
    </div>

</div>

<button id="btn_prosseguir" class="btn btn-success btn-sm hide" type="submit">Proseguir >></button>
{!! Form::close() !!}


@section('js')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>

    <link rel="stylesheet" href="{!! asset('vendor/adminlte/plugins/daterangepicker-master/daterangepicker.css') !!}">
    <script type="text/javascript" src="{!! asset('vendor/adminlte/plugins/daterangepicker-master/moment.min.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('vendor/adminlte/plugins/daterangepicker-master/daterangepicker.js') !!}"></script>

    <script>
        function validaCampos(nascimento){
            var sexo = $('#sexo').val();

            if(nascimento!=null && sexo != "0" ){
                var data_atual = moment();
                //se o intervalo de data é pelo menos maior que 6 meses
                if(data_atual.diff(nascimento,'months') >= 6){
                    //mostra o botão prosseguir
                    $('#btn_prosseguir').removeClass('hide');
                    $('#msg_erro').html('');
                }else{
                    $('#msg_erro').html('É preciso ter pelo menos 6 meses de idade para poder realizar o cadastro.');
                    $('#btn_prosseguir').addClass('hide');
                }
            }else{
                $('#msg_erro').html('É preciso ter pelo menos 6 meses de idade para poder realizar o cadastro.<br>É preciso selecionar o sexo.');
                $('#btn_prosseguir').addClass('hide');
            }
        }

        $(function () {

            $('#sexo').on('change',function(){
                validaCampos(moment([$('#nascimento').val()]));
            });

            //var linkEdit = '{{route('orgaos.edit',999)}}'; /***config***/
            $('#nascimento').daterangepicker({
                "showDropdowns": true,
                "singleDatePicker": true,
                "format": 'YYYY-MM-DD',
                "locale": datepickrangerLocale
            }, function(start,b,c) {
                validaCampos(moment(start.format('YYYY-MM-DD')));
            });

        });
    </script>
@stop

resources/views/portal/cadastro/etapa2.blade.php
@inject('request', 'Illuminate\Http\Request')

@section('css')
    <link rel="stylesheet" href="{!! asset('vendor/adminlte/plugins/daterangepicker-master/daterangepicker.css') !!}">
@stop




{!! Form::open(['route' => $rota]) !!}

<input type="hidden" name="_method" value="put" />
<input type="hidden" name="nascimento" value="{{$nascimento}}">
<input type="hidden" name="sexo" value="{{$sexo}}">

<div class="form-group">
    <label>Data de Nascimento</label>
    <h4>
        @php
            echo date("d/m/Y",strtotime($nascimento));
        @endphp
    </h4>
</div>
<div class="form-group">
    <label>Sexo</label>
    <h4>
        @switch($sexo)
        @case('m')
            Masculino
            @break
        @case('f')
            Feminino
            @break
        @endswitch
    </h4>
</div>
<div class="form-group">
    <label>Nome Completo (conforme RG)</label>
        <select name="name" id="nome_completo" class="form-control" ></select>
</div>
<button id="btn_prosseguir" class="btn btn-success btn-sm hide" type="submit">Proseguir >></button>
{!! Form::close() !!}


<style>
    .select2-container{z-index: 9999991 !important; color:red!important; }
    .select2-container .selection{z-index: 9999992 !important;}
    .select2-container .selection .select2-selection{z-index: 9999993 !important;}
    .select2-container .selection .select2-selection .select2-selection__rendered{z-index: 9999994 !important;}
    .select2-container .selection .select2-selection .select2-selection__rendered .select2-search{z-index: 9999995 !important;}
    .select2-container .selection .select2-selection .select2-selection__rendered .select2-search .select2-search__field{z-index: 9999996 !important;}
    select2-container input{text-transform: uppercase!important;}
</style>

@section('js')
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/css/select2.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/select2/4.0.3/js/select2.min.js"></script>
    <script src="{!! asset('js/select2-pt-BR.js') !!}"></script>

    <link rel="stylesheet" href="{!! asset('vendor/adminlte/plugins/daterangepicker-master/daterangepicker.css') !!}">
    <script type="text/javascript" src="{!! asset('vendor/adminlte/plugins/daterangepicker-master/moment.min.js') !!}"></script>
    <script type="text/javascript" src="{!! asset('vendor/adminlte/plugins/daterangepicker-master/daterangepicker.js') !!}"></script>


    <script>
        $(function () {


             $('#nome_completo').select2({
                 language: "pt-BR",
                minimumInputLength: 3,
                 allowClear: true,
                 placeholder: "Nome Completo",
                ajax: {
                    url: '{{route('portal.users.json')}}',
                    dataType: 'json',
                    cache: false,
                    delay: 1000,
                    data: function (params) {
                        params.page = (params.page) ? params.page:0;
                        var query = {
                            columns: [
                                {
                                    data: 'id',
                                    searchable : false,
                                    orderable : false,
                                    'search': {
                                        value: ''
                                    }
                                },{
                                    data: 'name',
                                    searchable : true,
                                    orderable : false,
                                    'search': {
                                        value: params.term?params.term:''
                                    }
                                },{
                                    data: 'nascimento',
                                    searchable : true,
                                    orderable : false,
                                    'search': {
                                        value: '{{$nascimento}}'
                                    }
                                },{
                                    data: 'sexo',
                                    searchable : true,
                                    orderable : false,
                                    'search': {
                                        value: '{{$sexo}}'
                                    }
                                }
                            ],
                            order: [{
                                column: 1,
                                dir : 'asc'
                            }],
                            draw : 1,
                            start :  (params.page*50),
                            length : 500,
                            '_': Math.random()
                        };
                        return query;
                    },
                    processResults: function (data,params) {
                        var arr = Object.values(data.data);

                        @if($request->route()->getName()!="portal.senha.etapas")
                        arr.push({id: $('.select2-search__field')[0].value , text: 'Cadastrar: '+$('.select2-search__field')[0].value});
                        @endif

                        return {
                            results: dat = JSON.parse(JSON.stringify(arr).split('name').join('text')),
                            pagination: {
                                more: (params.page*50+data.recordsTotal)  < data.recordsFiltered
                            }
                        };
                    }
                }
            }).on('select2:select', function (e) {
                var data = e.params.data;
                console.log(data);
                 $('#btn_prosseguir').removeClass('hide');
            });

        });
    </script>
@stop

resources/views/portal/cadastro/index.blade.php
@extends('layouts.portal')

@section('content')

<div class="container main-container">

    <div class="container home-banner">
        <div class="row">
            <div class="col-md-12">
                <div class="green-bar">

                </div>
            </div>
        </div>
        <div class="row">

        </div>
        <div class="row welcoming-bottom">

        </div>
    </div>
    <div class="container calendar">


    </div>
</div>
@stop